document.addEventListener('DOMContentLoaded', () => { lucide.createIcons(); const accordionItems = document.querySelectorAll('.accordion-item'); accordionItems.forEach(item => { const header = item.querySelector('.accordion-header'); header.addEventListener('click', () => { const isActive = item.classList.contains('active'); accordionItems.forEach(other => { if (other !== item) { other.classList.remove('active'); } }); item.classList.toggle('active', !isActive); }); }); const observerOptions = { root: null, rootMargin: '0px', threshold: 0.1 }; const observer = new IntersectionObserver((entries, obs) => { entries.forEach(entry => { if (entry.isIntersecting) { entry.target.classList.add('visible'); obs.unobserve(entry.target); } }); }, observerOptions); document.querySelectorAll('.reveal-card').forEach(el => observer.observe(el)); const navbar = document.querySelector('.navbar'); window.addEventListener('scroll', () => { navbar.classList.toggle('scrolled', window.scrollY > 50); }); const menuBtn = document.getElementById('mobile-menu-btn'); const navLinks = document.getElementById('nav-links'); const menuCloseBtn = document.getElementById('menu-close-btn'); const menuOverlay = document.getElementById('menu-overlay'); function openMenu() { navLinks.classList.add('open'); menuOverlay.classList.add('active'); document.body.style.overflow = 'hidden'; } function closeMenu() { navLinks.classList.remove('open'); menuOverlay.classList.remove('active'); document.body.style.overflow = ''; } if (menuBtn) menuBtn.addEventListener('click', openMenu); if (menuCloseBtn) menuCloseBtn.addEventListener('click', closeMenu); if (menuOverlay) menuOverlay.addEventListener('click', closeMenu); if (navLinks) { navLinks.querySelectorAll('a').forEach(link => { link.addEventListener('click', closeMenu); }); } const carousel = document.querySelector('.testimonials-carousel'); const dots = document.querySelectorAll('.carousel-dots .dot'); if (carousel && dots.length) { carousel.addEventListener('scroll', () => { const cardWidth = carousel.querySelector('.testimonial-card').offsetWidth + 16; const index = Math.round(carousel.scrollLeft / cardWidth); dots.forEach(d => d.classList.remove('active')); if (dots[index]) dots[index].classList.add('active'); }, { passive: true }); dots.forEach((dot, i) => { dot.addEventListener('click', () => { const cardWidth = carousel.querySelector('.testimonial-card').offsetWidth + 16; carousel.scrollTo({ left: i * cardWidth, behavior: 'smooth' }); }); }); }});

const scrollMilestones = [25, 50, 75, 100];
const reached = new Set();
window.addEventListener('scroll', () => {
  const scrolled = Math.round((window.scrollY / (document.body.scrollHeight - window.innerHeight)) * 100);
  scrollMilestones.forEach(milestone => {
    if (scrolled >= milestone && !reached.has(milestone)) {
      reached.add(milestone);
      gtag('event', 'scroll_depth', {event_category: 'Engajamento', event_label: milestone + '%'});
    }
  });
});
